import pandas as pd

data = [
    {"No.": 1, "Item": "LapTop Bags", "Sub-Item": "", "Quantity": "9", "Unit": "pieces"},
    {"No.": 2, "Item": "Lamp Shade", "Sub-Item": "", "Quantity": "3", "Unit": "pieces"},
    {"No.": 3, "Item": "Maasai Shuka", "Sub-Item": "", "Quantity": "3", "Unit": "pieces"},
    {"No.": 4, "Item": "Table BakuBaku", "Sub-Item": "", "Quantity": "28", "Unit": "pieces"},
    {"No.": 5, "Item": "Pochi Basi", "Sub-Item": "Small", "Quantity": "5", "Unit": "pieces"},
    {"No.": 5, "Item": "Pochi Basi", "Sub-Item": "Big", "Quantity": "5", "Unit": "pieces"},
    {"No.": 6, "Item": "Table Matt Visude", "Sub-Item": "Big", "Quantity": "1", "Unit": "piece"},
    {"No.": 6, "Item": "Table Matt Visude", "Sub-Item": "Medium", "Quantity": "4", "Unit": "pieces"},
    {"No.": 6, "Item": "Table Matt Visude", "Sub-Item": "Small", "Quantity": "10", "Unit": "pieces"},
    {"No.": 7, "Item": "Mifuko", "Sub-Item": "Mama Africa", "Quantity": "7", "Unit": "pieces"},
    {"No.": 7, "Item": "Mifuko", "Sub-Item": "Zimbabwe", "Quantity": "5", "Unit": "pieces"},
    {"No.": 7, "Item": "Mifuko", "Sub-Item": "Kilimanjaro", "Quantity": "10", "Unit": "pieces"},
    {"No.": 8, "Item": "Chesses Game", "Sub-Item": "Soft Stone", "Quantity": "5", "Unit": "pieces (4+1)"},
    {"No.": 8, "Item": "Chesses Game", "Sub-Item": "Wooden", "Quantity": "2", "Unit": "pieces"},
    {"No.": 9, "Item": "Heavy Blanket", "Sub-Item": "", "Quantity": "10", "Unit": "pieces"},
    {"No.": 10, "Item": "Pochi Uganda", "Sub-Item": "", "Quantity": "4", "Unit": "pieces"},
    {"No.": 11, "Item": "Kigoda", "Sub-Item": "", "Quantity": "1", "Unit": "pcs"},
    {"No.": "", "Item": "Kiti ngozi", "Sub-Item": "", "Quantity": "1", "Unit": "pcs"},
    {"No.": "", "Item": "Ba Bowl Stool (Nairobi)", "Sub-Item": "", "Quantity": "1", "Unit": "pcs"},
    {"No.": 11, "Item": "Salad spoon", "Sub-Item": "Mpingu", "Quantity": "19", "Unit": "pairs"},
    {"No.": 11, "Item": "Salad spoon", "Sub-Item": "Nairobi : Medium", "Quantity": "14", "Unit": "pairs"},
    {"No.": 11, "Item": "Salad spoon", "Sub-Item": "Nairobi : Small", "Quantity": "21", "Unit": "pairs"},
    {"No.": 11, "Item": "Salad spoon", "Sub-Item": "Mfupa", "Quantity": "4", "Unit": "pairs"},
    {"No.": "", "Item": "Karam spoons", "Sub-Item": "", "Quantity": "96", "Unit": "pieces"},
    {"No.": "", "Item": "Chop Sticks", "Sub-Item": "wood", "Quantity": "9", "Unit": "pairs"},
    {"No.": "", "Item": "Chop Sticks", "Sub-Item": "Bone", "Quantity": "3", "Unit": "pairs"},
    {"No.": "", "Item": "Chop Sticks", "Sub-Item": "metal", "Quantity": "10", "Unit": "pcs"},
    {"No.": 12, "Item": "Pencils", "Sub-Item": "", "Quantity": "23", "Unit": "pieces"},
    {"No.": 13, "Item": "Hereni", "Sub-Item": "", "Quantity": "122", "Unit": "pairs"},
    {"No.": 14, "Item": "Wallets", "Sub-Item": "MBao", "Quantity": "1", "Unit": "pair"},
    {"No.": 14, "Item": "Wallets", "Sub-Item": "Kitambaa", "Quantity": "19", "Unit": "pairs"},
    {"No.": 14, "Item": "Wallets", "Sub-Item": "Ngozi", "Quantity": "1", "Unit": "pieces"},
    {"No.": 18, "Item": "Soft Stone", "Sub-Item": "wanyama Small", "Quantity": "37", "Unit": "pieces"},
    {"No.": 18, "Item": "Soft Stone", "Sub-Item": "wanyama Medium", "Quantity": "66", "Unit": "pieces"},
    {"No.": 18, "Item": "Soft Stone", "Sub-Item": "wanyama Big", "Quantity": "19", "Unit": "pieces"},
    {"No.": "", "Item": "Coasters", "Sub-Item": "", "Quantity": "14", "Unit": "pieces"},
    {"No.": "", "Item": "Virombe", "Sub-Item": "", "Quantity": "6", "Unit": "pieces"},
    {"No.": "", "Item": "Sahani", "Sub-Item": "Big", "Quantity": "9", "Unit": "pieces"},
    {"No.": "", "Item": "Sahani", "Sub-Item": "Medium", "Quantity": "5", "Unit": "pieces"},
    {"No.": "", "Item": "Sahani", "Sub-Item": "Small", "Quantity": "24", "Unit": "pieces (17+7)"},
    {"No.": "", "Item": "Sahani (Boat Like)", "Sub-Item": "Big", "Quantity": "11", "Unit": "pieces"},
    {"No.": "", "Item": "Sahani (Boat Like)", "Sub-Item": "Small", "Quantity": "4", "Unit": "pcs"},
    {"No.": "", "Item": "Tissue holder", "Sub-Item": "", "Quantity": "7", "Unit": "pieces"},
    {"No.": 15, "Item": "Malakait", "Sub-Item": "Egg", "Quantity": "1", "Unit": "piece"},
    {"No.": 15, "Item": "Malakait", "Sub-Item": "Cats", "Quantity": "6", "Unit": "pieces"},
    {"No.": 16, "Item": "Dust Bin", "Sub-Item": "", "Quantity": "1", "Unit": "pcs"},
    {"No.": 17, "Item": "Vikombe", "Sub-Item": "Bati", "Quantity": "13", "Unit": "pieces"},
    {"No.": 17, "Item": "Vikombe", "Sub-Item": "Udongo", "Quantity": "5", "Unit": "pieces"},
    {"No.": 17, "Item": "Vikombe", "Sub-Item": "Glass", "Quantity": "5", "Unit": "pieces"},
    {"No.": 17, "Item": "Vikombe", "Sub-Item": "Bao", "Quantity": "1", "Unit": "pieces"},
    {"No.": 18, "Item": "Short Glass", "Sub-Item": "", "Quantity": "45", "Unit": "pieces"},
    {"No.": 19, "Item": "Sugar holder", "Sub-Item": "", "Quantity": "18", "Unit": "pieces"},
    {"No.": 20, "Item": "Salt Shaker", "Sub-Item": "", "Quantity": "7", "Unit": "pairs"},
    {"No.": 21, "Item": "Bao Game", "Sub-Item": "", "Quantity": "1", "Unit": "pieces"},
    {"No.": 22, "Item": "Candle holder (Metal)", "Sub-Item": "Big", "Quantity": "2", "Unit": "pairs"},
    {"No.": 22, "Item": "Candle holder (Metal)", "Sub-Item": "Medium", "Quantity": "5", "Unit": "pairs (3+2)"},
    {"No.": 22, "Item": "Candle holder (Metal)", "Sub-Item": "Small", "Quantity": "7", "Unit": "pairs (4+3)"},
    {"No.": "", "Item": "Mpingu (wood)", "Sub-Item": "Big", "Quantity": "3", "Unit": "pairs"},
    {"No.": "", "Item": "Mpingu (wood)", "Sub-Item": "Medium", "Quantity": "2", "Unit": "pairs"},
    {"No.": "", "Item": "Maasai Candle (Nairobi)", "Sub-Item": "", "Quantity": "5", "Unit": "pairs"},
    {"No.": "", "Item": "Maasai Candle (Mpingu)", "Sub-Item": "", "Quantity": "3", "Unit": "pieces"},
    {"No.": "", "Item": "Maasai Candle (Note)", "Sub-Item": "Maasai", "Quantity": "5", "Unit": "pcs"},
    {"No.": 23, "Item": "Ramani (Mfupa)", "Sub-Item": "", "Quantity": "2", "Unit": "pieces"},
    {"No.": 23, "Item": "Ramani (Kisara)", "Sub-Item": "small", "Quantity": "4", "Unit": "pieces"},
    {"No.": 23, "Item": "Ramani (Kisara)", "Sub-Item": "Big", "Quantity": "3", "Unit": "pieces"},
    {"No.": 23, "Item": "Birds hanger", "Sub-Item": "", "Quantity": "2", "Unit": "pcs"},
    {"No.": 24, "Item": "Kanawa", "Sub-Item": "", "Quantity": "3", "Unit": "pieces"},
    {"No.": 25, "Item": "Wanyama", "Sub-Item": "Zebra", "Quantity": "3", "Unit": "pieces"},
    {"No.": 25, "Item": "Wanyama", "Sub-Item": "Twiga", "Quantity": "14", "Unit": "pieces"},
    {"No.": 25, "Item": "Wanyama", "Sub-Item": "Ndege", "Quantity": "21", "Unit": "pieces"},
    {"No.": 25, "Item": "Wanyama", "Sub-Item": "Simba", "Quantity": "1", "Unit": "pieces"},
    {"No.": 25, "Item": "Wanyama", "Sub-Item": "Kitenge", "Quantity": "6", "Unit": "pieces"},
    {"No.": 25, "Item": "Wanyama", "Sub-Item": "Crocodile", "Quantity": "4", "Unit": "pieces"},
    {"No.": 26, "Item": "Coasters (Mpingu)", "Sub-Item": "", "Quantity": "18", "Unit": "pieces (17+1)"},
    {"No.": 27, "Item": "Tissue holder (Nairobi)", "Sub-Item": "", "Quantity": "4", "Unit": "pieces"},
    {"No.": "", "Item": "Jewelry Box", "Sub-Item": "", "Quantity": "7", "Unit": "pieces"},
    {"No.": "", "Item": "Candle holder", "Sub-Item": "Big", "Quantity": "1", "Unit": "pair"},
    {"No.": "", "Item": "Candle holder", "Sub-Item": "small", "Quantity": "3", "Unit": "pair"},
    {"No.": 28, "Item": "Pochi (Nairobi)", "Sub-Item": "", "Quantity": "8", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Shanga (philo)", "Quantity": "69", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Alice", "Quantity": "32", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Shanga (Nairobi)", "Quantity": "30", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Copper Brass Big", "Quantity": "3", "Unit": "pcs"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Copper Brass Small", "Quantity": "37", "Unit": "pcs"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Copper Brass Medium", "Quantity": "5", "Unit": "pcs"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Brass copper", "Quantity": "15", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Malakit", "Quantity": "13", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Shells", "Quantity": "4", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Mfupa", "Quantity": "7", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Ngozi", "Quantity": "29", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Uzi", "Quantity": "28", "Unit": "pcs (26+2)"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Plastic", "Quantity": "10", "Unit": "pcs"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Beads", "Quantity": "12", "Unit": "pieces"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Maasai", "Quantity": "6", "Unit": "pcs"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Bendera", "Quantity": "18", "Unit": "pcs"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Gurod", "Quantity": "11", "Unit": "pcs"},
    {"No.": 29, "Item": "Blackies (Bangles)", "Sub-Item": "Aluminium", "Quantity": "1", "Unit": "lp"},
    {"No.": 30, "Item": "Menu Box", "Sub-Item": "", "Quantity": "9", "Unit": "pieces"},
    {"No.": 31, "Item": "Kofia", "Sub-Item": "Conanga", "Quantity": "4", "Unit": "pieces"},
    {"No.": 31, "Item": "Kofia", "Sub-Item": "plain", "Quantity": "7", "Unit": "pieces"},
    {"No.": 31, "Item": "Kofia", "Sub-Item": "special", "Quantity": "2", "Unit": "pieces"},
    {"No.": 31, "Item": "Kofia", "Sub-Item": "Safari", "Quantity": "11", "Unit": "pieces (1+10)"},
    {"No.": 32, "Item": "T-Shirt (Embreydary)", "Sub-Item": "", "Quantity": "36", "Unit": "pieces (34+2)"},
    {"No.": 32, "Item": "T-Shirt", "Sub-Item": "Jezi", "Quantity": "0", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Maasai", "Quantity": "14", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Ngozi", "Quantity": "2", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Shanga", "Quantity": "18", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Mfupa", "Quantity": "13", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Ngoma", "Quantity": "16", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Wanyama", "Quantity": "18", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Monkey", "Quantity": "7", "Unit": "pieces"},
    {"No.": 33, "Item": "Key holder", "Sub-Item": "Mbao", "Quantity": "18", "Unit": "pieces"},
    {"No.": 34, "Item": "Hair bands", "Sub-Item": "Nairobi", "Quantity": "13", "Unit": "Piece"},
    {"No.": 34, "Item": "Hair bands", "Sub-Item": "Hair clip Shanga", "Quantity": "8", "Unit": "pieces"},
    {"No.": 34, "Item": "Hair bands", "Sub-Item": "Mfupa", "Quantity": "3", "Unit": "pieces"},
    {"No.": 35, "Item": "Soap dish", "Sub-Item": "", "Quantity": "6", "Unit": "pieces"},
    {"No.": 36, "Item": "Pensil Carrier", "Sub-Item": "", "Quantity": "2", "Unit": "pieces"},
    {"No.": 37, "Item": "Mikanda", "Sub-Item": "", "Quantity": "2", "Unit": "pieces"},
    {"No.": 38, "Item": "Spices", "Sub-Item": "", "Quantity": "5", "Unit": "pieces"},
    {"No.": 39, "Item": "Tissue Holder Mfupa", "Sub-Item": "", "Quantity": "13", "Unit": "pieces"},
    {"No.": 40, "Item": "Soaps Eucalyptus", "Sub-Item": "", "Quantity": "5", "Unit": "pieces"},
    {"No.": 41, "Item": "Coasters Mgomba", "Sub-Item": "", "Quantity": "5", "Unit": "pieces"},
    {"No.": 42, "Item": "Spices", "Sub-Item": "Canned", "Quantity": "2", "Unit": "cans"},
    {"No.": 42, "Item": "Spices", "Sub-Item": "Packed (Zanzibar)", "Quantity": "10", "Unit": "packets"},
    {"No.": 43, "Item": "Vipepeo", "Sub-Item": "", "Quantity": "3", "Unit": "pieces"},
    {"No.": 44, "Item": "Opener", "Sub-Item": "Mfupa", "Quantity": "16", "Unit": "pieces"},
    {"No.": 44, "Item": "Opener", "Sub-Item": "Mbao", "Quantity": "3", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Maasai", "Quantity": "4", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Nairobi", "Quantity": "23", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Philo", "Quantity": "26", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Old", "Quantity": "7", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Meru", "Quantity": "1", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Animal", "Quantity": "3", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Garden Necklace Nairobi", "Quantity": "19", "Unit": "pcs"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Choker", "Quantity": "33", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Uganda (Choker)", "Quantity": "5", "Unit": "pieces"},
    {"No.": 45, "Item": "Necklace", "Sub-Item": "Mawe (Choker)", "Quantity": "5", "Unit": "pcs"},
    {"No.": 46, "Item": "Mitandio", "Sub-Item": "Mwepesi", "Quantity": "18", "Unit": "pieces"},
    {"No.": 46, "Item": "Mitandio", "Sub-Item": "Mizito", "Quantity": "17", "Unit": "pieces (11+6)"},
    {"No.": "", "Item": "Pareo", "Sub-Item": "", "Quantity": "8", "Unit": "pieces"},
    {"No.": "", "Item": "Scarfs Tanzania", "Sub-Item": "", "Quantity": "5", "Unit": "pieces"},
    {"No.": 47, "Item": "Christmas House", "Sub-Item": "", "Quantity": "3", "Unit": "pieces"},
    {"No.": "", "Item": "Christmas Tree", "Sub-Item": "Big", "Quantity": "4", "Unit": "pcs"},
    {"No.": "", "Item": "Christmas Tree", "Sub-Item": "small", "Quantity": "3", "Unit": "pcs"},
    {"No.": 47, "Item": "Christmas Bells", "Sub-Item": "Angle Shanga", "Quantity": "21", "Unit": "pieces"},
    {"No.": 47, "Item": "Christmas Bells", "Sub-Item": "Nyota Big", "Quantity": "13", "Unit": "pieces"},
    {"No.": 47, "Item": "Christmas Bells", "Sub-Item": "Nyota (Other)", "Quantity": "7", "Unit": "pieces"},
    {"No.": 50, "Item": "Picha Frame", "Sub-Item": "", "Quantity": "7", "Unit": "pieces"},
    {"No.": 51, "Item": "Kayamba", "Sub-Item": "", "Quantity": "2", "Unit": "pieces"},
    {"No.": 52, "Item": "Mipira ya Gundi", "Sub-Item": "", "Quantity": "2", "Unit": "pieces"},
    {"No.": 53, "Item": "Tonga", "Sub-Item": "Small", "Quantity": "17", "Unit": "pcs (15+2)"},
    {"No.": 53, "Item": "Tonga", "Sub-Item": "Medium", "Quantity": "2", "Unit": ""},
    {"No.": 53, "Item": "Tonga", "Sub-Item": "Big", "Quantity": "1", "Unit": ""},
    {"No.": 54, "Item": "Makapu", "Sub-Item": "Singida", "Quantity": "12", "Unit": "pieces"},
    {"No.": 54, "Item": "Makapu", "Sub-Item": "Mtwara", "Quantity": "8", "Unit": "pieces"},
    {"No.": 54, "Item": "Makapu", "Sub-Item": "Nairobi - Uzi Big", "Quantity": "2", "Unit": "pcs"},
    {"No.": 54, "Item": "Makapu", "Sub-Item": "Nairobi - Uzi small", "Quantity": "2", "Unit": "pcs"},
    {"No.": 54, "Item": "Makapu", "Sub-Item": "Katani Medium", "Quantity": "5", "Unit": "pc"},
    {"No.": 54, "Item": "Makapu", "Sub-Item": "Katani Big", "Quantity": "3", "Unit": "pc"},
    {"No.": 54, "Item": "Makapu", "Sub-Item": "Nylon", "Quantity": "2", "Unit": "pieces"},
    {"No.": "", "Item": "Fruit Basket", "Sub-Item": "", "Quantity": "3", "Unit": "pieces"},
    {"No.": "", "Item": "Kapu pochi", "Sub-Item": "", "Quantity": "4", "Unit": "pieces"},
    {"No.": "", "Item": "Pochi ndogo katani", "Sub-Item": "", "Quantity": "4", "Unit": "pieces"},
    {"No.": "", "Item": "Pochi Lether", "Sub-Item": "", "Quantity": "1", "Unit": "pcs"},
    {"No.": 55, "Item": "Pensi Pareo", "Sub-Item": "", "Quantity": "5", "Unit": "pcs"},
    {"No.": "", "Item": "Cooking Hepron", "Sub-Item": "", "Quantity": "8", "Unit": "pcs"},
    {"No.": 56, "Item": "Table Matt Singida", "Sub-Item": "with Shanga Big", "Quantity": "44", "Unit": "pcs"},
    {"No.": 56, "Item": "Table Matt Singida", "Sub-Item": "Plain Big", "Quantity": "27", "Unit": "pcs (24+3)"},
    {"No.": 56, "Item": "Table Matt Rwanda", "Sub-Item": "Big", "Quantity": "4", "Unit": "pcs"},
    {"No.": 56, "Item": "Table Matt Rwanda", "Sub-Item": "Medium", "Quantity": "9", "Unit": "pcs"},
    {"No.": 56, "Item": "Table Matt Rwanda", "Sub-Item": "Small", "Quantity": "5", "Unit": "pcs"},
    {"No.": "", "Item": "Bakuli Singida", "Sub-Item": "with Shanga Medium", "Quantity": "14", "Unit": "pcs"},
    {"No.": 57, "Item": "Tray Rwanda (wood)", "Sub-Item": "Big", "Quantity": "3", "Unit": "pics"},
    {"No.": 58, "Item": "Table Matts Mgomba", "Sub-Item": "Big", "Quantity": "23", "Unit": "pcs"},
    {"No.": 58, "Item": "Table Matts Nyasi", "Sub-Item": "Big", "Quantity": "3", "Unit": "pcs"},
    {"No.": 59, "Item": "Bicycle", "Sub-Item": "", "Quantity": "5", "Unit": "pces"},
    {"No.": 60, "Item": "Bakuli Uganda", "Sub-Item": "Big", "Quantity": "3", "Unit": "pcs (2+1)"},
    {"No.": 60, "Item": "Bakuli Uganda", "Sub-Item": "small", "Quantity": "4", "Unit": "pcs"},
    {"No.": 61, "Item": "Bakuli Rwanda", "Sub-Item": "Big", "Quantity": "4", "Unit": "pcs (3+1)"},
    {"No.": 61, "Item": "Bakuli Rwanda", "Sub-Item": "Medium", "Quantity": "17", "Unit": "pcs"},
    {"No.": 61, "Item": "Bakuli Rwanda", "Sub-Item": "Small", "Quantity": "15", "Unit": "pcs"}
]

df = pd.DataFrame(data)
df.to_csv("Inventory_Stock_2025_2026.csv", index=False)
print("CSV saved.")